name: CI/CD AWS Deploy

on:
  push:
    branches: [ main ]

jobs:
#First we will see the application build or not , then we will deploy in EC2
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

  Deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2 
      - name: Deploy in EC2
        run: |
          ssh -i ${{secrets.AWS_PRIVATE_KEY}} ${{secrets.USER_NAME}}@${{secrets.HOSTNAME}}
          
            #Now we have got the access of EC2 and we will start the deploy
            cd /peixePOP &&
            git checkout main &&
            git fetch --all &&
            git reset --hard origin/main &&
            git pull origin main
